services:
  # app:
  #   build: .
  #   ports:
  #     - "9000:9000"

 db:
    image: postgres:16
    container_name: mygo-postgres
    restart: always
    environment:
      POSTGRES_USER: mygo-todo
      POSTGRES_PASSWORD: mygo-todo
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: