server:
  port: 9000

database:
  host: localhost
  user: mygo-todo
  password: mygo-todo
  port: 5432
  name: mydb
  sslmode: disable
  timezone: Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  max_life_time: 1h
